#!/bin/sh
#
# Generate the FrontAccounting configuration, then start Apache.
#
# Unlike the sibling stack in the FrontAccounting repo, the FA tree here is
# image content rather than someone's working copy: it is cloned at build time
# and thrown away with the container. So the four files FA needs but does not
# ship — they hold per-installation settings and are all gitignored — are
# written here, on every start, from the environment. There is nothing of anyone's
# to overwrite, and no host-side state to drift out of step with the container.
#
# The bind-mounted module at modules/sgw_sales is never touched.
set -eu

FA_ROOT="${FA_ROOT:-/var/www/html}"

# ---------------------------------------------------------------------------
# xdebug
# ---------------------------------------------------------------------------
#
# FrontAccounting guards its xdebug calls with function_exists('xdebug_call_file')
# — includes/db/connect_db_mysqli.inc, in the $go_debug branch that runs on every
# query. Under xdebug 3 that guard is wrong: the function exists whenever the
# extension is loaded but throws unless xdebug.mode includes 'develop'. An idle
# extension at mode=off therefore breaks every request instead of sitting out of
# the way, so it has to be unloaded rather than merely disabled.
#
# XDEBUG_MODE is fixed when the container is created, so changing it in
# docker/.env needs `fa-sgw-sales up`, which recreates, not `fa-sgw-sales restart`.
if command -v phpdismod >/dev/null 2>&1; then
    case "${XDEBUG_MODE:-off}" in
        ''|off) phpdismod -v "${PHP_VERSION:-ALL}" xdebug 2>/dev/null || true ;;
        *)      phpenmod  -v "${PHP_VERSION:-ALL}" xdebug 2>/dev/null || true ;;
    esac
fi

# ---------------------------------------------------------------------------
# FrontAccounting configuration
# ---------------------------------------------------------------------------

cat > "$FA_ROOT/config_db.php" <<EOF
<?php
/*
	Written by docker/docker-entrypoint.sh on every container start. Points at
	the 'db' service of the compose stack, reachable under that name from inside
	this container only.
*/

\$def_coy = 0;

\$tb_pref_counter = 1;

\$db_connections = array (
  0 =>
  array (
    'name' => 'Docker',
    'host' => '${FA_DB_HOST:-db}',
    'dbuser' => '${FA_DB_USER:-fa}',
    'dbpassword' => '${FA_DB_PASSWORD:-fa}',
    'dbname' => '${FA_DB_NAME:-fa_test}',
    'tbpref' => '${FA_DB_PREFIX:-0_}',
  ),
);
EOF

# config.default.php is FA's own template and tracks whatever FA_REF was cloned,
# so copying it is more durable than keeping a copy of it here. Left alone if it
# already exists, which only happens across a restart of the same container.
if [ ! -f "$FA_ROOT/config.php" ]; then
    cp "$FA_ROOT/config.default.php" "$FA_ROOT/config.php"
fi

# Two extension lists, not one: the root file says what is installed, the
# per-company one what is active for that company, and an absent per-company
# file is a fatal include rather than an empty list. Neither is in a clone —
# both are generated by FA's own extension installer in a real setup.
#
# The module is registered and activated in both, so includes/hooks.inc loads
# hooks.php, and hooks_sgw_sales' menu entries and security areas exist the way
# they would once someone had been through Setup -> Install/Activate
# Extensions. What that screen also does is run sql/update_1.0.sql through
# activate_extension(); here `fa-sgw-sales up` loads the module's schema instead.
# Written on every start: they are image content, and this is the only author.
write_extensions() {
    mkdir -p "$(dirname "$1")"
    cat > "$1" <<EOF
<?php

/* Written by docker/docker-entrypoint.sh. See the FrontAccounting extension
	system documentation for the format. */

\$next_extension_id = 2;

\$installed_extensions = array (
  1 =>
  array (
    'package' => 'sgw_sales',
    'name' => 'sgw_sales',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/sgw_sales',
    'active' => $2,
  ),
);
EOF
}
write_extensions "$FA_ROOT/installed_extensions.php" false
write_extensions "$FA_ROOT/company/0/installed_extensions.php" 1

if [ ! -f "$FA_ROOT/lang/installed_languages.inc" ]; then
    mkdir -p "$FA_ROOT/lang"
    cat > "$FA_ROOT/lang/installed_languages.inc" <<'EOF'
<?php

/* Written by docker/docker-entrypoint.sh. */

$installed_languages = array (
  0 =>
  array (
    'code' => 'C',
    'name' => 'English',
    'encoding' => 'iso-8859-1',
    'version' => '1',
  ),
);

$dflt_lang = 'C';
EOF
fi

# FA writes its error log and login-failure counter to tmp/.
mkdir -p "$FA_ROOT/tmp" \
         "$FA_ROOT/company/0/js_cache" \
         "$FA_ROOT/company/0/pdf_files" \
         "$FA_ROOT/company/0/backup"
chown -R www-data:www-data "$FA_ROOT/tmp" "$FA_ROOT/company" 2>/dev/null || true

# Not sourcing /etc/apache2/envvars here on purpose: it references variables it
# has not set yet, so under `set -u` it aborts with "APACHE_CONFDIR: parameter
# not set". apache2ctl sources it itself, with the right shell options.
#
# The run directory is normally made by the init system, which a container does
# not have, and a pid file left by an unclean stop makes Apache refuse to start.
mkdir -p /var/run/apache2
rm -f /var/run/apache2/apache2.pid

exec "$@"
